const accidents = [
  {
    X: "-79.3666955",
    Y: "43.65926703",
    Index_: "80564319",
    ACCNUM: "6001211373",
    YEAR: "2016",
    DATE: "2016-07-11T04:00:00.000Z",
    TIME: "27",
    Hour: "0",
    STREET1: "429 DUNDAS ST E",
    STREET2: "",
    OFFSET: "15 m North of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65926703",
    LONGITUDE: "-79.3666955",
    LOCCOORD: "Intersection",
    ACCLOC: "Intersection Related",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.",
    CYCACT: "Other",
    CYCCOND: "Had Been Drinking",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D51",
    Ward_Name: "Toronto Centre-Rosedale (28)",
    Ward_ID: "28",
    Hood_ID: "73",
    Hood_Name: "Moss Park (73)",
    FID: "1",
  },
  {
    X: "-79.43996058",
    Y: "43.65093954",
    Index_: "80503245",
    ACCNUM: "6000478020",
    YEAR: "2016",
    DATE: "2016-03-20T04:00:00.000Z",
    TIME: "344",
    Hour: "3",
    STREET1: "COLLEGE ST",
    STREET2: "LANSDOWNE AVE",
    OFFSET: "",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65093954",
    LONGITUDE: "-79.43996058",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "30 to 34",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Other",
    CYCCOND: "Had Been Drinking",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Davenport (18)",
    Ward_ID: "18",
    Hood_ID: "83",
    Hood_Name: "Dufferin Grove (83)",
    FID: "7",
  },
  {
    X: "-79.44399029",
    Y: "43.65804538",
    Index_: "7793636",
    ACCNUM: "1345603",
    YEAR: "2013",
    DATE: "2013-03-10T05:00:00.000Z",
    TIME: "400",
    Hour: "4",
    STREET1: "BLOOR ST W",
    STREET2: "ST HELENS AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65804538",
    LONGITUDE: "-79.44399029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Turning Right",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist turns right across motorists path",
    CYCACT: "Improper Turn",
    CYCCOND: "Other",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Davenport (18)",
    Ward_ID: "18",
    Hood_ID: "83",
    Hood_Name: "Dufferin Grove (83)",
    FID: "11",
  },
  {
    X: "-79.40648279",
    Y: "43.65665014",
    Index_: "80503369",
    ACCNUM: "6000543310",
    YEAR: "2016",
    DATE: "2016-03-31T04:00:00.000Z",
    TIME: "637",
    Hour: "6",
    STREET1: "COLLEGE ST",
    STREET2: "LIPPINCOTT ST",
    OFFSET: "1 m East of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65665014",
    LONGITUDE: "-79.40648279",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Rain",
    LIGHT: "Daylight, artificial",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "65 to 69",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "78",
    Hood_Name: "Kensington-Chinatown (78)",
    FID: "12",
  },
  {
    X: "-79.31184778",
    Y: "43.68340643",
    Index_: "80159337",
    ACCNUM: "4002017268",
    YEAR: "2014",
    DATE: "2014-05-05T04:00:00.000Z",
    TIME: "644",
    Hour: "6",
    STREET1: "WOODBINE AVE",
    STREET2: "MERRILL AVE E",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.68340643",
    LONGITUDE: "-79.31184778",
    LOCCOORD: "Intersection",
    ACCLOC: "Intersection Related",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "55 to 59",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D55",
    Ward_Name: "Beaches-East York (32)",
    Ward_ID: "32",
    Hood_ID: "64",
    Hood_Name: "Woodbine Corridor (64)",
    FID: "19",
  },
  {
    X: "-79.33171473",
    Y: "43.66672476",
    Index_: "80160040",
    ACCNUM: "4002062071",
    YEAR: "2014",
    DATE: "2014-05-12T04:00:00.000Z",
    TIME: "740",
    Hour: "7",
    STREET1: "DUNDAS ST E",
    STREET2: "LESLIE ST",
    OFFSET: "",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66672476",
    LONGITUDE: "-79.33171473",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "40 to 44",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist turning right on green or amber at signalized intersection strikes cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D55",
    Ward_Name: "Toronto-Danforth (30)",
    Ward_ID: "30",
    Hood_ID: "70",
    Hood_Name: "South Riverdale (70)",
    FID: "24",
  },
  {
    X: "-79.37704096",
    Y: "43.77126272",
    Index_: "80241812",
    ACCNUM: "5001016196",
    YEAR: "2015",
    DATE: "2015-06-17T04:00:00.000Z",
    TIME: "830",
    Hour: "8",
    STREET1: "ARROWSTOOK RD",
    STREET2: "BURBANK DR",
    OFFSET: "",
    ROAD_CLASS: "Local",
    District: "North York",
    LATITUDE: "43.77126272",
    LONGITUDE: "-79.37704096",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "60 to 64",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Failed to Yield Right of Way",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D33",
    Ward_Name: "Willowdale (24)",
    Ward_ID: "24",
    Hood_ID: "52",
    Hood_Name: "Bayview Village (52)",
    FID: "26",
  },
  {
    X: "-79.42467127",
    Y: "43.67918738",
    Index_: "80632459",
    ACCNUM: "6000853484",
    YEAR: "2016",
    DATE: "2016-05-18T04:00:00.000Z",
    TIME: "845",
    Hour: "8",
    STREET1: "580 CHRISTIE ST",
    STREET2: "",
    OFFSET: "2 m East of",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.67918738",
    LONGITUDE: "-79.42467127",
    LOCCOORD: "Mid-Block",
    ACCLOC: "At/Near Private Drive",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D13",
    Ward_Name: "St. Paul's (21)",
    Ward_ID: "21",
    Hood_ID: "94",
    Hood_Name: "Wychwood (94)",
    FID: "30",
  },
  {
    X: "-79.27853022",
    Y: "43.78527792",
    Index_: "80632217",
    ACCNUM: "6001699155",
    YEAR: "2016",
    DATE: "2016-09-24T04:00:00.000Z",
    TIME: "903",
    Hour: "9",
    STREET1: "MIDLAND AVE",
    STREET2: "SHEPPARD AVE E",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Scarborough",
    LATITUDE: "43.78527792",
    LONGITUDE: "-79.27853022",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "10 to 14",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Other",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D42",
    Ward_Name: "Scarborough-Rouge River (41)",
    Ward_ID: "41",
    Hood_ID: "128",
    Hood_Name: "Agincourt South-Malvern West (128)",
    FID: "32",
  },
  {
    X: "-79.30791865",
    Y: "43.67391928",
    Index_: "80159363",
    ACCNUM: "4002018320",
    YEAR: "2014",
    DATE: "2014-05-05T04:00:00.000Z",
    TIME: "1009",
    Hour: "10",
    STREET1: "WOODBINE AVE",
    STREET2: "KINGSTON RD",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.67391928",
    LONGITUDE: "-79.30791865",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "50 to 54",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D55",
    Ward_Name: "Beaches-East York (32)",
    Ward_ID: "32",
    Hood_ID: "63",
    Hood_Name: "The Beaches (63)",
    FID: "35",
  },
  {
    X: "-79.55492029",
    Y: "43.62899359",
    Index_: "80248481",
    ACCNUM: "5001450991",
    YEAR: "2015",
    DATE: "2015-08-23T04:00:00.000Z",
    TIME: "1147",
    Hour: "11",
    STREET1: "DUNDAS ST W",
    STREET2: "CLOVERDALE MALL",
    OFFSET: "100 m East of",
    ROAD_CLASS: "Major Arterial",
    District: "Etobicoke York",
    LATITUDE: "43.62899359",
    LONGITUDE: "-79.55492029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "55 to 59",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Stopped",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist loses control and strikes cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D22",
    Ward_Name: "Etobicoke-Lakeshore (5)",
    Ward_ID: "5",
    Hood_ID: "14",
    Hood_Name: "Islington-City Centre West (14)",
    FID: "40",
  },
  {
    X: "-79.34819029",
    Y: "43.69364538",
    Index_: "7828768",
    ACCNUM: "1360626",
    YEAR: "2013",
    DATE: "2013-06-12T04:00:00.000Z",
    TIME: "1157",
    Hour: "11",
    STREET1: "O CONNOR DR",
    STREET2: "RIVERCOURT BLVD",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.69364538",
    LONGITUDE: "-79.34819029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "35 to 39",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Turning Left",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist turned left across motorists path.",
    CYCACT: "Improper Turn",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D54",
    Ward_Name: "Toronto-Danforth (29)",
    Ward_ID: "29",
    Hood_ID: "58",
    Hood_Name: "Old East York (58)",
    FID: "45",
  },
  {
    X: "-79.4248086",
    Y: "43.64300497",
    Index_: "80490828",
    ACCNUM: "5001806026",
    YEAR: "2015",
    DATE: "2015-10-20T04:00:00.000Z",
    TIME: "1250",
    Hour: "12",
    STREET1: "QUEEN ST W",
    STREET2: "BEACONSFIELD AVE",
    OFFSET: "60 m West of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.64300497",
    LONGITUDE: "-79.4248086",
    LOCCOORD: "Intersection",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Overtaking",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist struck opened vehicle door",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Davenport (18)",
    Ward_ID: "18",
    Hood_ID: "84",
    Hood_Name: "Little Portugal (84)",
    FID: "47",
  },
  {
    X: "-79.48573695",
    Y: "43.64830359",
    Index_: "80248167",
    ACCNUM: "5001433281",
    YEAR: "2015",
    DATE: "2015-08-20T04:00:00.000Z",
    TIME: "1318",
    Hour: "13",
    STREET1: "SOUTH KINGSWAY",
    STREET2: "BLOOR ST W",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Etobicoke York",
    LATITUDE: "43.64830359",
    LONGITUDE: "-79.48573695",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Rain",
    LIGHT: "Daylight",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Parkdale-High Park (13)",
    Ward_ID: "13",
    Hood_ID: "87",
    Hood_Name: "High Park-Swansea (87)",
    FID: "49",
  },
  {
    X: "-79.42026148",
    Y: "43.6548992",
    Index_: "80175682",
    ACCNUM: "4003007939",
    YEAR: "2014",
    DATE: "2014-09-29T04:00:00.000Z",
    TIME: "1325",
    Hour: "13",
    STREET1: "COLLEGE ST",
    STREET2: "SHAW ST",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.6548992",
    LONGITUDE: "-79.42026148",
    LOCCOORD: "Intersection",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "Pedestrian Crossover",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist without ROW drives into path of cyclist at inter, lnwy, dwy-Driver not turn.",
    CYCACT: "Failed to Yield Right of Way",
    CYCCOND: "Fatigue",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Trinity-Spadina (19)",
    Ward_ID: "19",
    Hood_ID: "81",
    Hood_Name: "Trinity-Bellwoods (81)",
    FID: "53",
  },
  {
    X: "-79.35822687",
    Y: "43.6639057",
    Index_: "80718306",
    ACCNUM: "6001569976",
    YEAR: "2016",
    DATE: "2016-09-04T04:00:00.000Z",
    TIME: "1400",
    Hour: "14",
    STREET1: "GERRARD ST E",
    STREET2: "RIVER ST",
    OFFSET: "80 m East of",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.6639057",
    LONGITUDE: "-79.35822687",
    LOCCOORD: "Mid-Block",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "65 to 69",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Changing Lanes",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.",
    CYCACT: "Improper Lane Change",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D51",
    Ward_Name: "Toronto Centre-Rosedale (28)",
    Ward_ID: "28",
    Hood_ID: "72",
    Hood_Name: "Regent Park (72)",
    FID: "55",
  },
  {
    X: "-79.38179029",
    Y: "43.64834538",
    Index_: "5376335",
    ACCNUM: "1045778",
    YEAR: "2008",
    DATE: "2008-05-26T04:00:00.000Z",
    TIME: "1410",
    Hour: "14",
    STREET1: "KING ST W",
    STREET2: "YORK ST",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.64834538",
    LONGITUDE: "-79.38179029",
    LOCCOORD: "Mid-Block",
    ACCLOC: "At Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Unknown",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist struck opened vehicle door",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D52",
    Ward_Name: "Toronto Centre-Rosedale (28)",
    Ward_ID: "28",
    Hood_ID: "76",
    Hood_Name: "Bay Street Corridor (76)",
    FID: "61",
  },
  {
    X: "-79.42564783",
    Y: "43.66197165",
    Index_: "80225388",
    ACCNUM: "4003521992",
    YEAR: "2014",
    DATE: "2014-12-20T05:00:00.000Z",
    TIME: "1410",
    Hour: "14",
    STREET1: "OSSINGTON AVE",
    STREET2: "BLOOR ST W",
    OFFSET: "15 m South of",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66197165",
    LONGITUDE: "-79.42564783",
    LOCCOORD: "Intersection",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Trinity-Spadina (19)",
    Ward_ID: "19",
    Hood_ID: "80",
    Hood_Name: "Palmerston-Little Italy (80)",
    FID: "63",
  },
  {
    X: "-79.38432703",
    Y: "43.78668555",
    Index_: "80632024",
    ACCNUM: "5000992370",
    YEAR: "2015",
    DATE: "2015-06-13T04:00:00.000Z",
    TIME: "1423",
    Hour: "14",
    STREET1: "FINCH AVE E",
    STREET2: "PAGE AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "North York",
    LATITUDE: "43.78668555",
    LONGITUDE: "-79.38432703",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "45 to 49",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist turns right at non-signal Inter.(stop, yield, no cont.,and dwy) and strikes cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D33",
    Ward_Name: "Willowdale (24)",
    Ward_ID: "24",
    Hood_ID: "52",
    Hood_Name: "Bayview Village (52)",
    FID: "66",
  },
  {
    X: "-79.38629029",
    Y: "43.65004538",
    Index_: "7486701",
    ACCNUM: "1324513",
    YEAR: "2012",
    DATE: "2012-11-07T05:00:00.000Z",
    TIME: "1437",
    Hour: "14",
    STREET1: "RICHMOND ST W",
    STREET2: "UNIVERSITY AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65004538",
    LONGITUDE: "-79.38629029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Fatal",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "55 to 59",
    INJURY: "Fatal",
    FATAL_NO: "38",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Unknown",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D52",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "76",
    Hood_Name: "Bay Street Corridor (76)",
    FID: "71",
  },
  {
    X: "-79.36809029",
    Y: "43.79004538",
    Index_: "4218164",
    ACCNUM: "990402",
    YEAR: "2007",
    DATE: "2007-08-27T04:00:00.000Z",
    TIME: "1441",
    Hour: "14",
    STREET1: "FINCH Aven E",
    STREET2: "LESLIE Stre",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "North York",
    LATITUDE: "43.79004538",
    LONGITUDE: "-79.36809029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "70 to 74",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Unknown",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D33",
    Ward_Name: "Willowdale (24)",
    Ward_ID: "24",
    Hood_ID: "49",
    Hood_Name: "Bayview Woods-Steeles (49)",
    FID: "74",
  },
  {
    X: "-79.48011408",
    Y: "43.72740515",
    Index_: "80254240",
    ACCNUM: "5001841929",
    YEAR: "2015",
    DATE: "2015-10-26T04:00:00.000Z",
    TIME: "1510",
    Hour: "15",
    STREET1: "WILSON AVE",
    STREET2: "JAMES FINLAY WAY",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "North York",
    LATITUDE: "43.72740515",
    LONGITUDE: "-79.48011408",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist turning right on red at signalized intersection strikes cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D31",
    Ward_Name: "York Centre (9)",
    Ward_ID: "9",
    Hood_ID: "26",
    Hood_Name: "Downsview-Roding-CFB (26)",
    FID: "76",
  },
  {
    X: "-79.40506373",
    Y: "43.68671377",
    Index_: "80238703",
    ACCNUM: "5000804946",
    YEAR: "2015",
    DATE: "2015-05-14T04:00:00.000Z",
    TIME: "1538",
    Hour: "15",
    STREET1: "DUNVEGAN RD",
    STREET2: "ST CLAIR AVE W",
    OFFSET: "",
    ROAD_CLASS: "Local",
    District: "Toronto East York",
    LATITUDE: "43.68671377",
    LONGITUDE: "-79.40506373",
    LOCCOORD: "Mid-Block",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D53",
    Ward_Name: "St. Paul's (22)",
    Ward_ID: "22",
    Hood_ID: "96",
    Hood_Name: "Casa Loma (96)",
    FID: "79",
  },
  {
    X: "-79.45850001",
    Y: "43.65112646",
    Index_: "80494906",
    ACCNUM: "5002136221",
    YEAR: "2015",
    DATE: "2015-12-13T05:00:00.000Z",
    TIME: "1556",
    Hour: "15",
    STREET1: "PARKSIDE DR",
    STREET2: "INDIAN VALLEY CRES",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65112646",
    LONGITUDE: "-79.45850001",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Rain",
    LIGHT: "Daylight",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Stopped",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle rear-ended the other.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Parkdale-High Park (14)",
    Ward_ID: "14",
    Hood_ID: "87",
    Hood_Name: "High Park-Swansea (87)",
    FID: "82",
  },
  {
    X: "-79.49798975",
    Y: "43.60234411",
    Index_: "7864814",
    ACCNUM: "1376061",
    YEAR: "2013",
    DATE: "2013-09-18T04:00:00.000Z",
    TIME: "1634",
    Hour: "16",
    STREET1: "LAKE SHORE BLVD W",
    STREET2: "DWIGHT AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Etobicoke York",
    LATITUDE: "43.60234411",
    LONGITUDE: "-79.49798975",
    LOCCOORD: "Intersection",
    ACCLOC: "",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Fatal",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "50 to 54",
    INJURY: "Fatal",
    FATAL_NO: "41",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Unknown",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Lost control",
    CYCCOND: "Unknown",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D22",
    Ward_Name: "Etobicoke-Lakeshore (6)",
    Ward_ID: "6",
    Hood_ID: "18",
    Hood_Name: "New Toronto (18)",
    FID: "87",
  },
  {
    X: "-79.34077845",
    Y: "43.65351446",
    Index_: "80251331",
    ACCNUM: "5001652822",
    YEAR: "2015",
    DATE: "2015-09-23T04:00:00.000Z",
    TIME: "1715",
    Hour: "17",
    STREET1: "BOOTH AVE",
    STREET2: "LAKE SHORE BLVD E",
    OFFSET: "1 m North of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65351446",
    LONGITUDE: "-79.34077845",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Stop Sign",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "40 to 44",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist turns right at non-signal Inter.(stop, yield, no cont.,and dwy) and strikes cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D55",
    Ward_Name: "Toronto-Danforth (30)",
    Ward_ID: "30",
    Hood_ID: "70",
    Hood_Name: "South Riverdale (70)",
    FID: "89",
  },
  {
    X: "-79.43539029",
    Y: "43.65984538",
    Index_: "7441191",
    ACCNUM: "1305359",
    YEAR: "2012",
    DATE: "2012-06-05T04:00:00.000Z",
    TIME: "1725",
    Hour: "17",
    STREET1: "BLOOR ST W",
    STREET2: "DUFFERIN ST",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65984538",
    LONGITUDE: "-79.43539029",
    LOCCOORD: "Intersection",
    ACCLOC: "",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "35 to 39",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist struck opened vehicle door",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Davenport (18)",
    Ward_ID: "18",
    Hood_ID: "83",
    Hood_Name: "Dufferin Grove (83)",
    FID: "99",
  },
  {
    X: "-79.34218989",
    Y: "43.67941244",
    Index_: "80770490",
    ACCNUM: "7001157981",
    YEAR: "2017",
    DATE: "2017-06-28T04:00:00.000Z",
    TIME: "1800",
    Hour: "18",
    STREET1: "DANFORTH AVE",
    STREET2: "WOODYCREST AVE",
    OFFSET: "33 m West of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.67941244",
    LONGITUDE: "-79.34218989",
    LOCCOORD: "Mid-Block",
    ACCLOC: "At/Near Private Drive",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "35 to 39",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D55",
    Ward_Name: "Toronto-Danforth (30)",
    Ward_ID: "30",
    Hood_ID: "69",
    Hood_Name: "Blake-Jones (69)",
    FID: "101",
  },
  {
    X: "-79.40382777",
    Y: "43.66658362",
    Index_: "80784057",
    ACCNUM: "7001781629",
    YEAR: "2017",
    DATE: "2017-10-01T04:00:00.000Z",
    TIME: "1815",
    Hour: "18",
    STREET1: "BLOOR ST W",
    STREET2: "SPADINA AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66658362",
    LONGITUDE: "-79.40382777",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Overtaking",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist turning right on green or amber at signalized intersection strikes cyclist.",
    CYCACT: "Failed to Yield Right of Way",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "",
    MOTORCYCLE: "",
    TRUCK: "Yes",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "79",
    Hood_Name: "University (79)",
    FID: "104",
  },
  {
    X: "-79.36649029",
    Y: "43.66064538",
    Index_: "5252137",
    ACCNUM: "1110181",
    YEAR: "2009",
    DATE: "2009-06-19T04:00:00.000Z",
    TIME: "1844",
    Hour: "18",
    STREET1: "PARLIAMENT ST",
    STREET2: "OAK ST",
    OFFSET: "",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66064538",
    LONGITUDE: "-79.36649029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Pedestrian Crossover",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "5 to 9",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist struck at PXO(cyclist either travel in same dir. as veh. or ride across xwalk)",
    CYCACT: "Other",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D51",
    Ward_Name: "Toronto Centre-Rosedale (28)",
    Ward_ID: "28",
    Hood_ID: "72",
    Hood_Name: "Regent Park (72)",
    FID: "110",
  },
  {
    X: "-79.59560786",
    Y: "43.71725805",
    Index_: "80178889",
    ACCNUM: "4003213460",
    YEAR: "2014",
    DATE: "2014-10-31T04:00:00.000Z",
    TIME: "1845",
    Hour: "18",
    STREET1: "REXDALE BLVD",
    STREET2: "HIGHWAY 27  S",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Etobicoke York",
    LATITUDE: "43.71725805",
    LONGITUDE: "-79.59560786",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Rain",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "75 to 79",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Unknown",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.",
    CYCACT: "Other",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D23",
    Ward_Name: "Etobicoke North (2)",
    Ward_ID: "2",
    Hood_ID: "1",
    Hood_Name: "West Humber-Clairville (1)",
    FID: "116",
  },
  {
    X: "-79.28389368",
    Y: "43.77314718",
    Index_: "7808074",
    ACCNUM: "1351606",
    YEAR: "2013",
    DATE: "2013-04-13T04:00:00.000Z",
    TIME: "1846",
    Hour: "18",
    STREET1: "KENNEDY RD",
    STREET2: "401 C E KENNEDY RAMP RD E",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Scarborough",
    LATITUDE: "43.77314718",
    LONGITUDE: "-79.28389368",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dusk",
    RDSFCOND: "Dry",
    ACCLASS: "Fatal",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "35 to 39",
    INJURY: "Fatal",
    FATAL_NO: "10",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Motorist without ROW drives into path of cyclist at inter, lnwy, dwy-Driver not turn.",
    CYCACT: "Driving Properly",
    CYCCOND: "Unknown",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "Yes",
    AG_DRIV: "Yes",
    REDLIGHT: "Yes",
    ALCOHOL: "Yes",
    DISABILITY: "",
    Division: "D41",
    Ward_Name: "Scarborough-Agincourt (40)",
    Ward_ID: "40",
    Hood_ID: "126",
    Hood_Name: "Dorset Park (126)",
    FID: "126",
  },
  {
    X: "-79.42473994",
    Y: "43.64942892",
    Index_: "80164619",
    ACCNUM: "4002366263",
    YEAR: "2014",
    DATE: "2014-06-19T04:00:00.000Z",
    TIME: "1930",
    Hour: "19",
    STREET1: "DUNDAS ST W",
    STREET2: "DOVERCOURT RD",
    OFFSET: "",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.64942892",
    LONGITUDE: "-79.42473994",
    LOCCOORD: "Intersection",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D14",
    Ward_Name: "Trinity-Spadina (19)",
    Ward_ID: "19",
    Hood_ID: "81",
    Hood_Name: "Trinity-Bellwoods (81)",
    FID: "129",
  },
  {
    X: "-79.40209589",
    Y: "43.66304358",
    Index_: "80207052",
    ACCNUM: "4001910374",
    YEAR: "2014",
    DATE: "2014-04-08T04:00:00.000Z",
    TIME: "1955",
    Hour: "19",
    STREET1: "HARBORD ST",
    STREET2: "SPADINA AVE",
    OFFSET: "25 m East of",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66304358",
    LONGITUDE: "-79.40209589",
    LOCCOORD: "Intersection",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Other",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist struck opened vehicle door",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D52",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "79",
    Hood_Name: "University (79)",
    FID: "131",
  },
  {
    X: "-79.51259029",
    Y: "43.72824538",
    Index_: "5374508",
    ACCNUM: "1044949",
    YEAR: "2008",
    DATE: "2008-06-25T04:00:00.000Z",
    TIME: "2040",
    Hour: "20",
    STREET1: "136 NEAMES CRES",
    STREET2: "",
    OFFSET: "",
    ROAD_CLASS: "Local",
    District: "Etobicoke York",
    LATITUDE: "43.72824538",
    LONGITUDE: "-79.51259029",
    LOCCOORD: "Mid-Block",
    ACCLOC: "",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Daylight",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "5 to 9",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Insufficient information (to determine cyclist crash type).",
    CYCACT: "Other",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D31",
    Ward_Name: "York West (7)",
    Ward_ID: "7",
    Hood_ID: "26",
    Hood_Name: "Downsview-Roding-CFB (26)",
    FID: "139",
  },
  {
    X: "-79.43539029",
    Y: "43.65984538",
    Index_: "7441256",
    ACCNUM: "1305383",
    YEAR: "2012",
    DATE: "2012-06-05T04:00:00.000Z",
    TIME: "2045",
    Hour: "20",
    STREET1: "DUFFERIN ST",
    STREET2: "BLOOR ST W",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.65984538",
    LONGITUDE: "-79.43539029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dusk",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "West",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Unknown",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D11",
    Ward_Name: "Davenport (18)",
    Ward_ID: "18",
    Hood_ID: "83",
    Hood_Name: "Dufferin Grove (83)",
    FID: "143",
  },
  {
    X: "-79.25279029",
    Y: "43.70394538",
    Index_: "5285165",
    ACCNUM: "1124595",
    YEAR: "2009",
    DATE: "2009-09-14T04:00:00.000Z",
    TIME: "2103",
    Hour: "21",
    STREET1: "KINGSTON RD",
    STREET2: "CLIFFSIDE DR",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Scarborough",
    LATITUDE: "43.70394538",
    LONGITUDE: "-79.25279029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dark",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "45 to 49",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Disobeyed Traffic Control",
    CYCCOND: "Ability Impaired, Alcohol Over .80",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D41",
    Ward_Name: "Scarborough Southwest (36)",
    Ward_ID: "36",
    Hood_ID: "122",
    Hood_Name: "Birchcliffe-Cliffside (122)",
    FID: "146",
  },
  {
    X: "-79.31689029",
    Y: "43.82134538",
    Index_: "7807811",
    ACCNUM: "1351458",
    YEAR: "2013",
    DATE: "2013-04-12T04:00:00.000Z",
    TIME: "2110",
    Hour: "21",
    STREET1: "STEELES Ave E",
    STREET2: "BIRCHMOUNT Rd",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "Scarborough",
    LATITUDE: "43.82134538",
    LONGITUDE: "-79.31689029",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "55 to 59",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "East",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Insufficient information (to determine cyclist crash type).",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D42",
    Ward_Name: "Scarborough-Agincourt (39)",
    Ward_ID: "39",
    Hood_ID: "116",
    Hood_Name: "Steeles (116)",
    FID: "151",
  },
  {
    X: "-79.40476618",
    Y: "43.66894873",
    Index_: "80494517",
    ACCNUM: "5002105318",
    YEAR: "2015",
    DATE: "2015-12-08T05:00:00.000Z",
    TIME: "2115",
    Hour: "21",
    STREET1: "LOWTHER AVE",
    STREET2: "SPADINA RD",
    OFFSET: "5 m South of",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.66894873",
    LONGITUDE: "-79.40476618",
    LOCCOORD: "Intersection",
    ACCLOC: "Intersection Related",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Rain",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Turning Left",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Cyclist turned left across motorists path.",
    CYCACT: "Improper Turn",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D53",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "95",
    Hood_Name: "Annex (95)",
    FID: "157",
  },
  {
    X: "-79.56346522",
    Y: "43.65320929",
    Index_: "80632055",
    ACCNUM: "6001283246",
    YEAR: "2016",
    DATE: "2016-07-21T04:00:00.000Z",
    TIME: "2127",
    Hour: "21",
    STREET1: "THE EAST MALL",
    STREET2: "RATHBURN RD",
    OFFSET: "137 m South of",
    ROAD_CLASS: "Minor Arterial",
    District: "Etobicoke York",
    LATITUDE: "43.65320929",
    LONGITUDE: "-79.56346522",
    LOCCOORD: "Mid-Block",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "20 to 24",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist reversing struck cyclist.",
    CYCACT: "Driving Properly",
    CYCCOND: "Other",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D22",
    Ward_Name: "Etobicoke Centre (3)",
    Ward_ID: "3",
    Hood_ID: "14",
    Hood_Name: "Islington-City Centre West (14)",
    FID: "162",
  },
  {
    X: "-79.39118586",
    Y: "43.71105917",
    Index_: "80777026",
    ACCNUM: "7000925099",
    YEAR: "2017",
    DATE: "2017-05-25T04:00:00.000Z",
    TIME: "2150",
    Hour: "21",
    STREET1: "MOUNT PLEASANT RD",
    STREET2: "BROADWAY AVE",
    OFFSET: "",
    ROAD_CLASS: "Major Arterial",
    District: "North York",
    LATITUDE: "43.71105917",
    LONGITUDE: "-79.39118586",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Rain",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Wet",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "65 to 69",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "North",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Motorist turned left across cyclists path.",
    CYCACT: "Driving Properly",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D53",
    Ward_Name: "St. Paul's (22)",
    Ward_ID: "22",
    Hood_ID: "99",
    Hood_Name: "Mount Pleasant East (99)",
    FID: "165",
  },
  {
    X: "-79.37352381",
    Y: "43.6608692",
    Index_: "80631117",
    ACCNUM: "4002525835",
    YEAR: "2014",
    DATE: "2014-07-18T04:00:00.000Z",
    TIME: "2240",
    Hour: "22",
    STREET1: "GERRARD ST E",
    STREET2: "PEMBROKE ST",
    OFFSET: "",
    ROAD_CLASS: "Minor Arterial",
    District: "Toronto East York",
    LATITUDE: "43.6608692",
    LONGITUDE: "-79.37352381",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Dark",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist without ROW rides into path of motorist at inter, lnwy, dwy-Cyclist not turn.",
    CYCACT: "Failed to Yield Right of Way",
    CYCCOND: "Had Been Drinking",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "Yes",
    AG_DRIV: "Yes",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D51",
    Ward_Name: "Toronto Centre-Rosedale (27)",
    Ward_ID: "27",
    Hood_ID: "73",
    Hood_Name: "Moss Park (73)",
    FID: "172",
  },
  {
    X: "-79.37693415",
    Y: "43.64681204",
    Index_: "80632014",
    ACCNUM: "5000859369",
    YEAR: "2015",
    DATE: "2015-05-21T04:00:00.000Z",
    TIME: "2255",
    Hour: "22",
    STREET1: "YONGE ST",
    STREET2: "FRONT ST E",
    OFFSET: "10 m North of",
    ROAD_CLASS: "Major Arterial",
    District: "Toronto East York",
    LATITUDE: "43.64681204",
    LONGITUDE: "-79.37693415",
    LOCCOORD: "Intersection",
    ACCLOC: "At Intersection",
    TRAFFCTL: "Traffic Signal",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "35 to 39",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Overtaking",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE:
      "Cyclist and Driver travelling in same direction. One vehicle sideswipes the other.",
    CYCACT: "Improper Passing",
    CYCCOND: "Normal",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D51",
    Ward_Name: "Toronto Centre-Rosedale (28)",
    Ward_ID: "28",
    Hood_ID: "77",
    Hood_Name: "Waterfront Communities-The Island (77)",
    FID: "175",
  },
  {
    X: "-79.39853297",
    Y: "43.65910681",
    Index_: "80772593",
    ACCNUM: "7000366630",
    YEAR: "2017",
    DATE: "2017-02-26T05:00:00.000Z",
    TIME: "2311",
    Hour: "23",
    STREET1: "215 HURON ST",
    STREET2: "",
    OFFSET: "20 m South of",
    ROAD_CLASS: "Local",
    District: "Toronto East York",
    LATITUDE: "43.65910681",
    LONGITUDE: "-79.39853297",
    LOCCOORD: "Mid-Block",
    ACCLOC: "Non Intersection",
    TRAFFCTL: "No Control",
    VISIBILITY: "Clear",
    LIGHT: "Dark, artificial",
    RDSFCOND: "Dry",
    ACCLASS: "Non-Fatal Injury",
    IMPACTYPE: "Cyclist Collisions",
    INVTYPE: "Cyclist",
    INVAGE: "25 to 29",
    INJURY: "Major",
    FATAL_NO: "",
    INITDIR: "South",
    VEHTYPE: "Bicycle",
    MANOEUVER: "Going Ahead",
    DRIVACT: "",
    DRIVCOND: "",
    PEDTYPE: "",
    PEDACT: "",
    PEDCOND: "",
    CYCLISTYPE: "Insufficient information (to determine cyclist crash type).",
    CYCACT: "Other",
    CYCCOND: "Inattentive",
    PEDESTRIAN: "",
    CYCLIST: "Yes",
    AUTOMOBILE: "Yes",
    MOTORCYCLE: "",
    TRUCK: "",
    TRSN_CITY_: "",
    EMERG_VEH: "",
    PASSENGER: "Yes",
    SPEEDING: "",
    AG_DRIV: "",
    REDLIGHT: "",
    ALCOHOL: "",
    DISABILITY: "",
    Division: "D52",
    Ward_Name: "Trinity-Spadina (20)",
    Ward_ID: "20",
    Hood_ID: "79",
    Hood_Name: "University (79)",
    FID: "179",
  },
];

module.exports = accidents;
